# Introduction of Pytorch and Neural Network
## By Allen Huang 

神经网络3blue1brown: https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi

In [15]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "http://www.marekrei.com/blog/wp-content/uploads/2014/02/neuralnetwork2.png",width=500, height=500)

Neural networks consist of a bunch of "neurons" which are values that start off as your input data, and then get multiplied by weights, summed together, and then passed through an activation function to produce new values, and this process then repeats over however many "layers" your neural network has to then produce an output.

The input(x1,x2,x3) data must be numerical. We call the input features, which could also be some sort of categorical type of feature. We need to convert the features(like color, length, how many legs) into numerical data. Pixel value is very commen. 

These input pass to hidden layers. We do not have control over these layers. In your hidden layers ("hidden" just generally refers to the fact that the programmer doesn't really set or control the values to these layers, the machine does), these are neurons, numbering in however many you want (you control how many there are, just not the value of those neurons), and then they lead to an output layer. 

The output is usually either a single neuron for regression tasks, or as many neurons as you have classes. In the above case, there are 2 output neurons, so maybe this neural network is classifying dogs vs cats. Each neuron's value can be thought of as a confidence score for if the neural network thinks it's that class. We just find out which one is the greatest, and that's the prediction of our neural networks.

Whichever neuron has the highest value, that's the predicted class! So maybe the top of the two output neurons is "dog" and then "cat" on the bottom. If the dog value is the largest one, then that would be the prediction of the neural network.

Connecting all of the neurons are those lines. Each of them is a weight, and possibly a bias. So the inputs get multiplied by the weights, the biases are added in, then it gets summed at the next neuron, passed through an activation function, to be the next input value for the next one!

In [19]:
# What goes on in a single neural?
Image(url= "https://pythonprogramming.net/static/images/machine-learning/artificial-neuron-model-sigmoid-activiation-function.png",width=700, height=500)

Above is an example of this "zoomed in" so to speak to show the mechanism for just a single neuron. You can see the inputs from other neurons come in, they're multiplied by the weights, bias are optionally added, then they are summed together. After this summation, they pass through an activation function. The activation function's job is to calculate whether or not, or how much, a neuron is "firing." A neuron could output a 0 or 1 to be off or on, but also, more commonly, could instead output a range between 0 and 1, for example, which serves as input to the next layer.

- Input: scaling down, to be between 0 and 1

- Weight and biases: parameter, machine have ability to modify every single one of these parameters independently.

### 1. What is Pytorch

The Pytorch library, like the other deep learning libraries, really is just a library that does operations on tensors.

What's a tensor?!

You can just think of a tensor like an array. Really all we're doing is basically multiplying arrays here. That's all there is to it. The fancy bits are when we run an optimization algorithm on all those weights to start modifying them. Neural networks themselves are actually super basic and simple. Their optimization is a little more challenging, but most of these deep learning libraries also help you a bit with that math. If you want to learn how to do everything yourself by hand, stay tuned later in the series. I just don't think it would be wise to lead with that.

__*download Pytorch using: conda install pytorch torchvision -c pytorch*__

In [26]:
# Pytorch is numpy on the GPU, tensor is an array
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


So yeah, it's just [5 2, 3 1]. Simple stuff!

Because it's a lot of operations on arrays, Pytorch aims to mimic the very popular numeric library in Python called NumPy. Many of the exact same methods exist, usually with the same names, but sometimes different ones. One common task is to make an "empty" array, of some shape. In NumPy, we use np.zeros. In Pytorch, we do the same!

In [28]:
# specify shape
x = torch.zeros([2,5])
print(x)
print(x.shape)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


In [29]:
y = torch.rand([2,5])
print(y)

tensor([[0.9468, 0.5984, 0.8497, 0.9162, 0.9963],
        [0.1323, 0.1449, 0.2750, 0.7287, 0.1380]])


In [30]:
# reshape 
y.view([1,10])

tensor([[0.9468, 0.5984, 0.8497, 0.9162, 0.9963, 0.1323, 0.1449, 0.2750, 0.7287,
         0.1380]])

In [31]:
y

tensor([[0.9468, 0.5984, 0.8497, 0.9162, 0.9963],
        [0.1323, 0.1449, 0.2750, 0.7287, 0.1380]])

In [32]:
# re-assign is needed 
y = y.view([1,10])
print(y)

tensor([[0.9468, 0.5984, 0.8497, 0.9162, 0.9963, 0.1323, 0.1449, 0.2750, 0.7287,
         0.1380]])
