1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
np.__version__

'1.17.2'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hkmac/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hkmac/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hkmac/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hkmac/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hkmac/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hkmac/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hkmac/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hkmac/anaconda3/include']


3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to get the documentation of the numpy add function from the command line?

python -c "import numpy; numpy.info(numpy.add)"

In [8]:
np.add?

5. Create a null vector of size 10 but the fifth value which is 1 

In [9]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49

In [12]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Reverse a vector (first element becomes last)

In [24]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

8. Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9. Find indices of non­zero elements from [1,2,0,0,4,0]

In [28]:
a = [1,2,0,0,4,0]
[i-1 for i in a if i != 0]

[0, 1, 3]

In [29]:
# better to use 
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

10. Create a 3x3 identity matrix 

In [33]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11. Create a 3x3x3 array with random values

In [35]:
np.random.random((3,3,3))

array([[[0.47857014, 0.70500391, 0.20798715],
        [0.73869623, 0.89843583, 0.70938604],
        [0.97506918, 0.62340099, 0.34265448]],

       [[0.71698954, 0.15466811, 0.28750014],
        [0.1748074 , 0.183004  , 0.67320044],
        [0.48913525, 0.67628889, 0.18973172]],

       [[0.58841668, 0.00443632, 0.03005777],
        [0.58767367, 0.98697702, 0.50582625],
        [0.14593775, 0.20692499, 0.54548902]]])

12. Create a 10x10 array with random values and find the minimum and maximum values

In [46]:
a = np.random.random((10,10))
np.min(a)

0.014086828017449982

In [47]:
np.max(a)

0.9891312576099589

In [48]:
# or 
a.max()

0.9891312576099589

In [49]:
a.min()

0.014086828017449982

13. Create a random vector of size 30 and find the mean value

In [52]:
a = np.random.random((1,30))

In [53]:
a.mean()

0.48164727909042576

In [54]:
# we can directly use 30 for size
a = np.random.random(30)

14. Create a 2d array with 1 on the border and 0 inside

In [68]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
a[:,[0,2]] = 1
a[[0,2],:] = 1

In [73]:
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [77]:
# better way
b = np.ones((3,3))
b[1,1] = 0
b

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

15. What is the result of the following expression?

In [79]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [103]:
a = np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])