## np.newaxis和数组维数

np.newaxis的作用就是在这一位置增加一个一维，这一位置指的是np.newaxis所在的位置

In [3]:
import numpy as np
x1 = np.array([1, 2, 3, 4, 5])

In [7]:
print(x1.shape,"\n",x1.ndim)
# 可以看出，x1是一个一维的数组，这时候我总会有一个问题，这个一维数组是一行还是一列

(5,) 
 1


In [8]:
# 要解决这个问题，不妨试试矩阵和向量的乘法
matrix = np.eye(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# 假设x1是1*5的行向量，而matrix是5*5，相乘得到1*5的行向量
x1.dot(matrix)

array([1., 2., 3., 4., 5.])

In [11]:
# 但是
matrix.dot(x1)

array([1., 2., 3., 4., 5.])

In [16]:
# 因此，一维数组既不是一个行向量，也不是一个列向量
# 使用reshape，我们将一维数组转化为行向量（注意，这时候数组的维度发生了改变）
x2 = x1.reshape(1,5)
x2

array([[1, 2, 3, 4, 5]])

In [17]:
print(x2.ndim)

2


In [18]:
x2.dot(matrix)

array([[1., 2., 3., 4., 5.]])

In [19]:
# 这样就没错了~！
matrix.dot(x2)

ValueError: shapes (5,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [22]:
# 那么newaxis是做什么呢？
x1

array([1, 2, 3, 4, 5])

In [23]:
# 这就是我们刚才所做的reshape的工作，数组的维度加一，而这个维度加在了行，也就是变成行向量
x1[np.newaxis,:]

array([[1, 2, 3, 4, 5]])

In [24]:
x3 = x1[np.newaxis,:]
print(x3.shape,"\n",x3.ndim)

(1, 5) 
 2


In [25]:
# 这样的话，则变成列向量
x4 = x1[:,np.newaxis]
print(x4.shape,"\n",x4.ndim)

(5, 1) 
 2


In [30]:
# 对于一个多维数组
x5 = np.arange(18).reshape(3,6)
print(x5.shape,"\n",x5.ndim)

(3, 6) 
 2


In [32]:
x6 = x5[:,np.newaxis]
print(x6.shape,"\n",x6.ndim)

(3, 1, 6) 
 3


In [33]:
x7 = x5[np.newaxis,:]
print(x7.shape,"\n",x7.ndim)
# 其规律是，在你选择的位置，插入一个1

(1, 3, 6) 
 3
